---
name: "cosmo-trigger"

services:
  cosmo-trigger:
    build: .
    container_name: "cosmo-trigger"
    network_mode: "host"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
